### PR TITLE
Custom request handlers feature

### PR DESCRIPTION
**Pull request by fjorgemota**
Hello.

This PR adds custom request handlers support to the package and remove HTTPS support by default, as the title already specifies, but okay.

The custom request handlers allow anyone to use anything (synchronous) they want to make the request. In my case, for example, I cannot use this python-kit because `requests` does not really likes AppEngine, for example. I think that other use cases is possible, but the fact that `requests` does not works on AppEngine is sufficient for me. =)

Other question is that I removed HTTPS support by default. There's three reasons for that:

1) prismic.io works natively without HTTPS. And not everyone needs HTTPS support by default;
2) HTTPS support needs a GCC compiler to compile the SSL support needed by the library;
3) AppEngine doesn't like C compiled modules; =P

Instead, I added the HTTPS support as an optional requeriment, which can be installed using something like `pip install prismic[https_support]`. And updated the tests to use HTTP instead of HTTPS, obviously. 

Oh, and the README is updated according to the these updates, too. =)

Well, that's everything. I expect that you may like the changes. (maybe you call me crazy by removing HTTPS support, but....seems good for me (as prismic.io really can work without HTTPS))

And...sorry for my (possible) poor english. 

That's it.

### CODE REVIEW

**Comment by erwan** [comment]
Hi,

Thank you very much! Allowing for custom HTTP handlers is a good idea, we're actually doing it already in other kits (PHP for example).

However I'm a bit reluctant to remove https by default, as for security reasons we want to encourage everyone to use https unless they really have no choice.  Is there no way HTTPS can work on Google App Engine?

**Comment by fjorgemota** [comment]
Hi.

Yes, HTTPS can work on AppEngine, however, C modules not. This is the
problem. And, for some reason, I found that prismic.io's SSL certificate
does not work with Python 2.7 on Ubuntu 12.04 (on Ubuntu 14.04 it works,
strange), do you know why? (it emits an alert about ssl v3 totally strange
for me) (just for curiosity)

I will try including the HTTPS support and testing at night.

Thanks for the feedback and the fast response. =)


Atenciosamente,
Fernando Jorge Mota,
http://www.fjorgemota.com  <http://www.fjorgemota.com>

2015-03-02 7:01 GMT-03:00 Erwan Loisant <notifications@github.com>:

**Comment by fjorgemota** [comment]
Well..

I tested here, and I can exclude the HTTPS requeriments of prismic of the requeriments.txt and it will not be included in the build. (I use gaenv to include the packages that I use on my project)

Because this I'll update my branch removing the commit that removes the HTTPS support by default.

**Comment by fjorgemota** [comment]
Updated. Can you check now, @erwan?

Thanks. =)

**Comment by fjorgemota** [comment]
A detail that I found now: To use prismic package on AppEngine, it's ideal to remove its dependency on `pkg_resources` to get informations from...itself.

That's because AppEngine does not have the concept of packages nor dependencies itself. Its all something like a ugly hack called [gaenv](https://pypi.python.org/pypi/gaenv) to allow the use of normal `requeriments.txt` and other normal python things, which does not implement something like pkg_resources support by default.

What you think about it? Can we remove easily pkg_resources easily of prismic package? It's ideal to put that on this same PR or other PR maybe will be ideal?

Thanks.

**Comment by fjorgemota** [comment]
Hey. 

I removed pkg_resources dependence of the package. How? Well, `pkg_resources` is being used only to detect the version of the package, what in theory is possible of doing just with something like `from . import __version__`, which I used.

More important than that is the fact that...the tests passed without modification, which theorically can prove my theory.

What you think, @erwan? :)

**Comment by erwan** [comment]
Thanks for the contribution - I need some time to review this PR, I'll come back to comment here soon :)

**Comment by fjorgemota** [comment]
Oh..it's ok for me.

Thanks! :)
